### ISSUE TITLE
On orthogonality penalty loss

### ISSUE THREAD

**Issue by CVxcj** [GT-RIPL/CODA-Prompt#12]
Hi authors, thanks for your wonderful work and code.
I see that the weight coefficient of the orthogonal loss term in your code defaults to 0. I tried to set it to 0.1 as set in your paper. It was found that the average accuracy actually decreased in the end.  Is there any problem with this? I would greatly appreciate it if you could reply to me.

**Comment by jamessealesmith** [comment]
Thank you for the comment; please see the note in our readme:

_We received feedback from other researchers that our orthogonality initialization might not be “in the spirit” of continual learning. So, we fixed it! Our code now uses the Gram-Schmidt process at the start of each new task to initialize new prompting parameters. We found that, with this initialization, we can even set the ortho penalty of our method to 0.0! We hope this might inspire future work, as well. Send me a message if you want to discuss more (email preferred)._

For more context, it seems that the Gram-Schmidt initialization is sufficient for the ortho penalty. If you want to explore the penalty more, I suggest you try much smaller numbers in the 1e-6 range.
