### ISSUE TITLE
Orthogonal penalty calculation

### ISSUE THREAD

**Issue by Fatflower** [GT-RIPL/CODA-Prompt#4]
def ortho_penalty(t):
    return ((t @t.T - torch.eye(t.shape[0]).cuda())**2).mean() * 1e-6

The above is the orthogonal penalty calculation in your zoo.py, but why multiply it by 1e-6, which is not explained in the paper?

**Comment by jamessealesmith** [comment]
Hi! This is part of the loss weighting value. Thank you for pointing out this error - I will incorporate this value into the updated configs in the next push and highlight it. Thank you again.
