### ISSUE TITLE
Reproducing issue for ImageNet-R dataset

### ISSUE THREAD

**Issue by SanghyeokSon** [GT-RIPL/CODA-Prompt#5]
Thanks for sharing your wonderful work!

I'm trying to run the code using the ImageNet-R dataset.
However, I obtained a lower performance than the results reported in the paper.
I checked all the details listed in the supplementary material.
Does it need additional techniques to achieve the performance of the paper?

Sincerely,

**Comment by jamessealesmith** [comment]
I will be pushing the ImageNet-R code soon, which should address any issues.
