### ISSUE TITLE
Reproducing issue for upper-bound

### ISSUE THREAD

**Issue by yuzhang0403** [GT-RIPL/CODA-Prompt#6]
Hi, thank you for your amazing paper.

I added two new parameters, 'oracle_flag' and 'upper_bound_flag,' to the **cifar-100.sh** and set the schedule to 200 in **cifar-100_prompt.yaml.** I conducted experiments both with and without coda-prompt, and the obtained results were significantly better than those reported in the paper, achieving accuracies of 91% and 94%, respectively. Moreover, it appears that the results can still be further improved with additional iterations. Similarly, on the ImageNet-R dataset, the accuracy achieved far surpasses what is documented in the paper. 

So, I am curious to understand how the 'upper_bound' is calculated.

**Comment by jamessealesmith** [comment]
This is a great finding! I used iterations with the same schedule as the continual learning methods. I also found in more recent work that the UB can be higher if you only train the QKV projection matrices of self-attention blocks - I think this should be the SOTA "upper bound" to consider in future work - https://arxiv.org/pdf/2304.06027.pdf
