### ISSUE TITLE
Calculation for Forgetting

### ISSUE THREAD

**Issue by coyoteling** [GT-RIPL/CODA-Prompt#7]
Hi, thanks for the amazing work!
We have run the code you provided, but we found that the results of the run did not contain the metrics for forgetting rate reported in the paper. We would like to know if you have provided the code to calculate the forgetting, or maybe we didn't find it. If it was not provided, we would like to know if you will upload if soon?
Thanks again!

**Comment by jamessealesmith** [comment]
It seems the averaging might differ from the definition in Wang’s paper (L2P/Dual Prompt). I uploaded the metric I used to utils/calc_forgetting.py (this metric is a common forgetting metric used in past papers including my own). All of the results in my paper used this same forgetting metric and thus are fair comparisons.
